[versions]
min-sdk = "23"
target-sdk = "36"
compile-sdk = "36"

agp = "9.0.0"
kotlin = "2.3.0"
ktor = "3.4.0"

[plugins]
kgp = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ks = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kmm = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
agp = { id = "com.android.application", version.ref = "agp" }
alp = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
cc = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }


[libraries]
# Kotlin
kotlinx-serialization-core = "org.jetbrains.kotlinx:kotlinx-serialization-core:1.10.0"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
kotlinx-io = "org.jetbrains.kotlinx:kotlinx-io-core:0.8.2"

ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-winhttp = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }

