[versions]
kotlin = "2.2.21"
ktor = "3.3.2"

[plugins]
kgp = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ks = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kmm = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[libraries]
# Kotlin
kotlinx-serialization-core = "org.jetbrains.kotlinx:kotlinx-serialization-core:1.9.0"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
kotlinx-io = "org.jetbrains.kotlinx:kotlinx-io-core:0.8.1"

ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-winhttp = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }

